version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: jammy
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: bionic
