name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@v1.0.2
    #- uses: eshork/gitleaks-action@v1.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag evryfs/docker-baseimage:$(date +%s)
    - run: echo ::set-output name=tag_name::$(head -1 Dockerfile | awk '{print $2}' | tr ':' ' '| awk '{print $2}')
      id: tagName
    - uses: anothrNick/github-tag-action@1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        RELEASE_BRANCHES: master
        CUSTOM_TAG: ${{ steps.tagName.outputs.tag_name }}
